### ISSUE TITLE
沚水大大，下载的小说文件在哪

### ISSUE THREAD

**Issue by 20020922zjj** [zsakvo/Cirno-go#16]
Cirno-go-main里没有多出txt或equb文件

**Comment by 20020922zjj** [comment]
writing out files…
download success!
出现这两句了，但是文件夹里没有多出txt文件或者equb文件啊

**Comment by gin32167** [comment]
一般会在用户文件夹下面有个cirno的文件夹

**Comment by 20020922zjj** [comment]
> 一般会在用户文件夹下面有个cirno的文件夹

这个我用搜索找到了，谢谢
