### ISSUE TITLE
沚水大大，我也出现了登陆失败请稍后再试

### ISSUE THREAD

**Issue by 20020922zjj** [zsakvo/Cirno-go#17]
第一次还能登陆，第二次登录时就不行了。请问那个备用方案是什么。我这里还是需要登陆，否则就显示缺少登陆参数

**Comment by gin32167** [comment]
这个是刺猬猫的登录验证，一天第一次登录不会验证，后面就需要验证导致的第二次登录不了，这需要抓包token，修改config文件夹来用；因为APP每次登录会重新获取token，最好先手机登录抓包token，再修改config，这样就可以长期用了

**Comment by 20020922zjj** [comment]
> 这个是刺猬猫的登录验证，一天第一次登录不会验证，后面就需要验证导致的第二次登录不了，这需要抓包token，修改config文件夹来用;因为APP每次登录会重新获取token，最好先手机登录抓包token，再修改config，这样就可以长期用了

明白了，谢谢

**Comment by AlexiaAshford** [comment]
刺猬猫新版本增加了 极验GEETEST 验证, 如果登录输入错误信息或者多次登入就会触发GEETEST 校验, 同IP可能需要迟几小时重新登入才不会触发校验, 可以尝试通过更换IP来避开校验触发

**Comment by AlexiaAshford** [comment]
也许你应该关闭这个issue了
