### ISSUE TITLE
请问登录账号、登录密码以及书号在代码中哪个地方输入呀？谢谢！

### ISSUE THREAD

**Issue by szdengxc** [zsakvo/Cirno-go#2]
还有运行代码结束后，抓出来的text文件会放在哪个文件夹呀？需要在代码中哪个位置设置一下吗？谢谢！

**Comment by zsakvo** [comment]
不需要设置，默认情况会把登陆凭证以及下载的书籍全都置于 $HOME/Cirno/ 文件夹下
但是目前我只在 MacOS ，Linux，以及 Android 上测试过，正常来讲 Windows 应该也是同样可以。
如果有什么问题的话可以进一步反馈。

**Comment by zsakvo** [comment]
登陆的话使用 cirno login 命令即可，按照提示输入账号密码，会自动把登录凭证保存到上述位置下，下次直接使用下载命令就好。
（readme 都写了……）
