### ISSUE TITLE
亲爱的，软件今天开始抓小说出错

### ISSUE THREAD

**Issue by szdengxc** [zsakvo/Cirno-go#4]
软件可以登录，但不能完成整个小说的抓取，是不是调整外挂库文件了呀？
出错信息如下：
![image](https://user-images.githubusercontent.com/76396399/107849679-e8079600-6e37-11eb-8a85-7c9c28d229e5.png)
敬请指点！谢谢

**Comment by zsakvo** [comment]
大过年的……好好休息吧
暂时懒得看，请理解，谢谢。

**Comment by szdengxc** [comment]
好的，有闲有兴致时候再看看吧，谢谢！祝春节愉快！

**Comment by zsakvo** [comment]
解密出错的时候直接执行了中断而非返回错误值导致的，等我有空改一下，应该就可以了。
不过具体什么情况会导致返回了不完整(?)的数据，还有待观察。

**Comment by szdengxc** [comment]
好的，非常感谢！



---原始邮件---
发件人: "沚水"<notifications@github.com&gt;
发送时间: 2021年2月24日(周三) 下午4:42
收件人: "zsakvo/Cirno-go"<Cirno-go@noreply.github.com&gt;;
抄送: "szdengxc"<szdengxc@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zsakvo/Cirno-go] 亲爱的，软件今天开始抓小说出错 (#4)




 
解密出错的时候直接执行了中断而非返回错误值导致的，等我有空改一下，应该就可以了。
 不过具体什么情况会导致返回了不完整(?)的数据，还有待观察。
