### ISSUE TITLE
冒昧的问一下.....抓取epub文件好像出错了.......

### ISSUE THREAD

**Issue by imdengxiaozhu** [zsakvo/Cirno-go#6]
按说明书抓取出来的epub文件无法被手机阅读器打开（多看，neat reader，QQ阅读器）.....自己从网上下的epub却可以........斗胆问一下如何抓出正确的epub文件并附带图片。万望大佬不吝赐教！

**Comment by imdengxiaozhu** [comment]
之前那个输错了，不好意思，添麻烦了🥺

**Comment by zsakvo** [comment]
怎么说呢 epub 格式的封装我是采用的 epub3.0 规范设计的，这个规范稍微有一点点新？（其实并没有很新，单纯是 epub 格式过于混乱导致的）

有些阅读器的 epub 读取似乎没实现对应的功能吧，我自己测试的时候使用 Mac 自带的 图书.app ，以及 Android 上的 多看，厚墨（2.x） 之类的是可以正常显示的

至于获取图片，按照此处自行添加对应的 config 参数就行了

![image](https://user-images.githubusercontent.com/25399519/110263121-a7430d00-7ff0-11eb-8ee4-92706ec6dbaa.png)

**Comment by imdengxiaozhu** [comment]
沚水，您好，我按照你提示的代码无法开启图片抓取功能，计算机提示命令无效，如附图所示，我应该在什么地方输入你提示的代码才能开启图片抓取功能呢？再就是我用安卓版“多看”等无法打开抓取下载的epub文件，如附图2所示第一本书。

![mmexport1615646910485](https://user-images.githubusercontent.com/80222786/111034329-12a53880-8450-11eb-94a3-a325973e8204.jpg)
![mmexport1615646383711](https://user-images.githubusercontent.com/80222786/111034334-15a02900-8450-11eb-9400-e373a17c2e90.png)
