### ISSUE TITLE
运行编译后的main.exe有问题

### ISSUE THREAD

**Issue by gin32167** [zsakvo/Cirno-go#8]
Windows中使用go build编辑后，直接点击main.exe没有反应，在cmd中运行又只会提示Please login first.，但是又登录不了，具体怎么操作？或者说怎么进行登录操作？
![image](https://user-images.githubusercontent.com/83170209/116033799-ac3d4800-a694-11eb-82f6-aa070b69b90a.png)

**Comment by jerryfangr** [comment]
> Windows中使用go build编辑后，直接点击main.exe没有反应，在cmd中运行又只会提示Please login first.，但是又登录不了，具体怎么操作？或者说怎么进行登录操作？
> ![image](https://user-images.githubusercontent.com/83170209/116033799-ac3d4800-a694-11eb-82f6-aa070b69b90a.png)

兄弟你看readme么，作者**Usage**下不是标注了使用方法么。

首先默认编译完的文件应该叫 Cirno .exe 或者 Cirno-go.exe，你main就main把，反正一个效果。

### 登录
```bash
cd "D:\Program Files\Cirno-go-main"
main.exe login
```

### 下载
```bash
cd "D:\Program Files\Cirno-go-main"
main.exe search 小说名
# 选择小说左侧的数字序号回车，下载
```

**Comment by gin32167** [comment]
谢谢，已经可以用了

**Comment by 20020922zjj** [comment]
大哥，你怎么弄得，我go build后好像不行
![39JW5IE)}~)U_MUU31E488E](https://user-images.githubusercontent.com/114208265/192093950-61533eb0-01e4-402e-8ff2-d46dfaea96d3.png)
![M){W4GSKD` DUD S8S)W(%C](https://user-images.githubusercontent.com/114208265/192093952-251c3893-4d48-499f-a6c6-3ddb737fddb9.png)
